[package]
name = "mnstrv2cli"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["all-widgets", "macros", "palette", "scrolling-regions", "serde"] }
